version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true  # Helps with file change detection

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Ensure the backend is exposed on port 8000
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
